### ISSUE TITLE
Questions for unified attestation

### ISSUE THREAD

**Issue by water5-cmd** [jinzhao-dev/jinzhao-attest#2]
Hi, developers!
Thank you very much for your outstanding work! 
I would like to ask if this project includes a stage for registering heterogeneous TEE nodes. 
In this stage, each heterogeneous TEE node generates a pair of public-private keys (ak.pub/ak.priv) that serve as identifiers for their own identity. The public key is sent to the UAS, and in return, the node receives the UAS root certificate and the AK (Attestation Key) certificate.

**Comment by jxiao1** [comment]
We don't define a stage for registering TEE nodes in UAL,  but we indeed maintain an identity keypair (UAK).  As default,  we will put the HASH of UAK.pub into the attestation report. This is always used to set up a trusted logical connection between two TEE instances.

**Comment by jxiao1** [comment]
In UAS, we support taking the attestation report as an identity certificate. This is not only for registering the TEE node but also for all cases where a trusted identity is required.
